# Generated by Django 5.2.8 on 2025-12-16 14:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='books_book_search__c24b82_gin'),
        ),
    ]
