# Generated by Django 5.2.8 on 2025-12-19 18:41

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_books_book_search__c24b82_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
