# Generated by Django 5.2.8 on 2025-12-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
