# Generated by Django 5.2.8 on 2025-12-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_views'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(help_text='0 to 90')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='books.book')),
            ],
        ),
    ]
